# always use absolute paths
# provide at least one parameter per option (no empty parameters allowed)

##### RESOURCES #####
# memory in MB
mem: '32000'
mem_small: '16000'
threads: 2
partition: 'shortq'

##### GENERAL #####
annotation: .test/config/digits_unsupervised_analysis_annotation.csv
result_path: .test/results/
project_name: digits

##### PCA #####
# (no configuration necessary)

##### UMAP & densMAP #####
# information on the various parameters: https://umap-learn.readthedocs.io/en/latest/parameters.html
# umap knn-graph will be generated for each metric once with the max(n_neighbors)
# knn-graph parameters: metrics (default: euclidean), n_neighbors (default: 15)
# embedding parameters: min_dist  (default: 0.1), n_components (default: 2)
# densmap flag: perform densMAP  (0==no, 1==yes) on top of UMAP with all parameter combinations (https://umap-learn.readthedocs.io/en/latest/densmap_demo.html)
# connectivity visualization flag (0==no, 1==yes), computational expensive (slow), recommendation 0 for exploration and 1 for validation
umap:
    metrics: ['euclidean']
    n_neighbors: [100]
    min_dist: [0.1]
    n_components: [2,3]
    densmap: 1
    connectivity: 1
    diagnostics: 1

##### HEATMAP #####
# information on the ComplexHeatmap parameters: https://jokergoo.github.io/ComplexHeatmap-reference/book/index.html
# distance metrics: for rows and columns. all metrics that are supported by stats::dist() (https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/dist) and 'pearson','spearman', and 'kendall'.
# clustering methods: methods for hierarchical clustering that are supported by stats::hclust() (https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/hclust)
# it is the most resource (memory) intensive method, leave empty [] if not required
heatmap:
    metrics: ['spearman']
    hclust_methods: ['complete']
    
##### VISUALIZATION #####
# 2D/3D visualization with ggplot2 and plotly
scatterplot2d:
    size: 1
    alpha: 1
    
# metadata column used for plotting of PCA pairs plot and ComplexHeatmaps annotation(or empty "", then first column of the metadata dataframe will be taken)
metadata_of_interest: "target"

# specify features of interest, which values from the data, will be highlgihted in the 2D/3D plots
# motivated by bioinformatics highlighting expression levels of marker genes (eg: ['PTPRC'])
# if not used leave empty []
features_to_plot: ['pixel_0_0','pixel_0_1','pixel_0_2','pixel_0_3']

